### PR TITLE
Output optimal h for kernel smoothing

### PR DESCRIPTION
**Pull request by jennyjyounglee**
I added two lines of code to output optimal h and estimated risk function values after implementing Kernel smoothing in estimate_npmetric_erf.R

### CODE REVIEW

**Comment by Naeemkh** [comment]
@jennyjyounglee, please explain why it is needed, also please update NEWS.md file.

**Comment by jennyjyounglee** [comment]
Outputting optimal h and risk value helps to better understand if specified bw_seq was adequate or not. For example, maybe suboptimal h at the end of range was chosen on a specified range but  it may not be optimal.

**Comment by Naeemkh** [comment]
@jennyjyounglee, Thanks. Please update the NEWS.md file, and also make sure that your branch is updated with the recent changes on the develop branch.

**Comment by Naeemkh** [comment]
Closing because of other PR #116

**Pull request closed without merging**
